steps:
  # Clone the Django repository from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/martinartaza/voting-app-django-backoffice.git', 'django-app']
    
  # Build the Docker image from the cloned repository
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/django-repo/django:latest', './django-app']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/django-repo/django:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'django-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/django-repo/django:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=20'
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=config.settings,DEBUG=False'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/django-repo/django:latest'

options:
  logging: CLOUD_LOGGING_ONLY 